name: 'Example: GitHub User Rank Tracker'

on:
  push:
    branches: [ main ]

jobs:
  track-user:
    runs-on: ubuntu-latest
    name: Track GitHub User Ranking
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: GitHub User Rank Tracker
        uses: maifeeulasad/my-github-rank@v1
        id: tracker
        with:
          username: 'maifeeulasad'
          days: '7'
          max-commits: '10'
          
      - name: Display Results
        run: |
          echo "Country: ${{ steps.tracker.outputs.country }}"
          echo "Followers Rank Change: ${{ steps.tracker.outputs.followers-rank-change }}"
          echo "Public Contributions Rank Change: ${{ steps.tracker.outputs.public-contributions-rank-change }}"
          echo "Total Contributions Rank Change: ${{ steps.tracker.outputs.total-contributions-rank-change }}"
          echo "Commits Analyzed: ${{ steps.tracker.outputs.commits-analyzed }}"
          echo "SVG Report: ${{ steps.tracker.outputs.svg-path }}"
          echo ""
          echo "Summary:"
          echo "${{ steps.tracker.outputs.summary }}"
          
      - name: Upload SVG Report
        uses: actions/upload-artifact@v4
        with:
          name: rank-progress-report
          path: ${{ steps.tracker.outputs.svg-path }}
          if-no-files-found: warn
